### ISSUE TITLE
Bonjour

### ISSUE THREAD

**Issue by Olpouin** [Powerock38/kevains-adventure#1]
J'ai un problème, c'est quoi qui va sortir en premier ? ORNE ou Kévain Adventure ?

**Comment by GitSquared** [comment]
@Olpouin Très bonne question. Il faudrai que @Powerock38 donne une date prévue pour Kévains Adventure et poser la question sur https://github.com/GitSquared/ORNE-client ...

**Comment by Powerock38** [comment]
dsl

**Comment by GitSquared** [comment]
@Powerock38 a défini la date prévue comme NaN, impossible de résoudre l'issue.
